### ISSUE TITLE
module err

### ISSUE THREAD

**Issue by VeryCalmDude** [Angelokh22/Minecraft-Gift_code-gen-Checker#1]
Traceback (most recent call last):
  File "C:\Users\tsk20\Desktop\hehe\main.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by Angelokh22** [comment]
> Traceback (most recent call last): File "C:\Users\tsk20\Desktop\hehe\main.py", line 6, in from selenium import webdriver ModuleNotFoundError: No module named 'selenium'

pip install selenium

**Comment by ZatrexReal** [comment]
ok
